<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRatTVlO\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRatTVlO/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerRatTVlO.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerRatTVlO\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerRatTVlO\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'RatTVlO',
    'container.build_id' => 'b5e38390',
    'container.build_time' => 1774547388,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRatTVlO');
