<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddDestinationControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Form\Destination\AddDestinationController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\Destination\AddDestinationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Form\\Destination\\AddDestinationController'] = new \Glpi\Controller\Form\Destination\AddDestinationController();
    }
}
