<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddNewHelpdeskTranslationControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Helpdesk\Translation\AddNewHelpdeskTranslationController' shared autowired service.
     *
     * @return \Glpi\Controller\Helpdesk\Translation\AddNewHelpdeskTranslationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Helpdesk\\Translation\\AddNewHelpdeskTranslationController'] = new \Glpi\Controller\Helpdesk\Translation\AddNewHelpdeskTranslationController();
    }
}
