<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCopyParentEntityControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Config\Helpdesk\CopyParentEntityController' shared autowired service.
     *
     * @return \Glpi\Controller\Config\Helpdesk\CopyParentEntityController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Config\\Helpdesk\\CopyParentEntityController'] = new \Glpi\Controller\Config\Helpdesk\CopyParentEntityController();
    }
}
