<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomIllustrationControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\UI\Illustration\CustomIllustrationController' shared autowired service.
     *
     * @return \Glpi\Controller\UI\Illustration\CustomIllustrationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\UI\\Illustration\\CustomIllustrationController'] = new \Glpi\Controller\UI\Illustration\CustomIllustrationController(($container->privates['Glpi\\UI\\IllustrationManager'] ??= new \Glpi\UI\IllustrationManager()));
    }
}
