<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexController3Service extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\ServiceCatalog\IndexController' shared autowired service.
     *
     * @return \Glpi\Controller\ServiceCatalog\IndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\ServiceCatalog\\IndexController'] = new \Glpi\Controller\ServiceCatalog\IndexController();
    }
}
