<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnowbaseItemControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Knowbase\KnowbaseItemController' shared autowired service.
     *
     * @return \Glpi\Controller\Knowbase\KnowbaseItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Knowbase\\KnowbaseItemController'] = new \Glpi\Controller\Knowbase\KnowbaseItemController();
    }
}
