<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailCollectorFormControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\ItemType\Form\MailCollectorFormController' shared autowired service.
     *
     * @return \Glpi\Controller\ItemType\Form\MailCollectorFormController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\ItemType\\Form\\MailCollectorFormController'] = new \Glpi\Controller\ItemType\Form\MailCollectorFormController();
    }
}
