<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressErrorListenerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the private 'Glpi\Kernel\Listener\ExceptionListener\ProgressErrorListener' shared autowired service.
     *
     * @return \Glpi\Kernel\Listener\ExceptionListener\ProgressErrorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Glpi\\Kernel\\Listener\\ExceptionListener\\ProgressErrorListener'] = new \Glpi\Kernel\Listener\ExceptionListener\ProgressErrorListener(($container->privates['Glpi\\Progress\\ProgressStorage'] ??= new \Glpi\Progress\ProgressStorage()));
    }
}
