<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\ProgressController' shared autowired service.
     *
     * @return \Glpi\Controller\ProgressController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\ProgressController'] = new \Glpi\Controller\ProgressController(($container->privates['Glpi\\Progress\\ProgressStorage'] ??= new \Glpi\Progress\ProgressStorage()));
    }
}
