<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStep3ResolveIssuesControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Form\Import\Step3ResolveIssuesController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\Import\Step3ResolveIssuesController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Form\\Import\\Step3ResolveIssuesController'] = new \Glpi\Controller\Form\Import\Step3ResolveIssuesController();
    }
}
