<?php

namespace ContainerRatTVlO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubmitAnswerControllerService extends Glpi_Kernel_KernelProductionContainer
{
    /*
     * Gets the public 'Glpi\Controller\Form\SubmitAnswerController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\SubmitAnswerController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Glpi\\Controller\\Form\\SubmitAnswerController'] = new \Glpi\Controller\Form\SubmitAnswerController(($container->services['logger'] ?? $container->get('logger', 1)));
    }
}
